### ISSUE TITLE
regex_dfa_equals

### ISSUE THREAD

**Issue by Prasad-AV** [jacger2/softregex#3]
Hello 

I want to know how "regex_dfa_equals.jar" is produced and what is its significance? Any details which you can share to understand this.

Thank you.

**Comment by jacger2** [comment]
I'm sorry for the late reply.

regex_dfa_equals.Jar is the file used to determine if the model generated regex is the same as the correct answer in the paper "deep-regex" that first generated NL-RX-Turk data. (It seems to check equivalent of two REGEX by changing REGEX to MDFA, https://arxiv.org/pdf/1608.03000.pdf)

In this paper ("SOFTREGEX"), the file was also used to generate data labels for models that learn the equivalence of regular expressions.

Thank you

**Comment by Prasad-AV** [comment]
Thank you for your email response.

Regards
Prasad
